// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package operators

import (
	"time"

	types "github.com/galxe/spotted-network/pkg/common/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Operators struct {
	Address                 string               `json:"address"`
	SigningKey              string               `json:"signing_key"`
	RegisteredAtBlockNumber uint64               `json:"registered_at_block_number"`
	RegisteredAtTimestamp   uint64               `json:"registered_at_timestamp"`
	ActiveEpoch             uint32               `json:"active_epoch"`
	ExitEpoch               uint32               `json:"exit_epoch"`
	Status                  types.OperatorStatus `json:"status"`
	Weight                  pgtype.Numeric       `json:"weight"`
	CreatedAt               time.Time            `json:"created_at"`
	UpdatedAt               time.Time            `json:"updated_at"`
}
