// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package operators

import (
	"context"

	types "github.com/galxe/spotted-network/pkg/common/types"
)

// TODO: change things here.
type Querier interface {
	// Create a new operator record with inactive status
	// -- invalidate: GetOperatorByAddress
	// -- timeout: 500ms
	CreateOperator(ctx context.Context, arg CreateOperatorParams, getOperatorByAddress *string) (*Operators, error)
	// Get operator information by address
	// -- cache: 168h
	// -- timeout: 500ms
	GetOperatorByAddress(ctx context.Context, address string) (*Operators, error)
	// Get all operators regardless of status
	// -- timeout: 1s
	ListAllOperators(ctx context.Context) ([]Operators, error)
	// Get all operators with a specific status
	// -- timeout: 1s
	ListOperatorsByStatus(ctx context.Context, status types.OperatorStatus) ([]Operators, error)
	// Update operator exit epoch
	// -- invalidate: GetOperatorByAddress
	// -- timeout: 500ms
	UpdateOperatorExitEpoch(ctx context.Context, arg UpdateOperatorExitEpochParams, getOperatorByAddress *string) (*Operators, error)
	// Update operator status and weight
	// -- invalidate: GetOperatorByAddress
	// -- timeout: 500ms
	UpdateOperatorState(ctx context.Context, arg UpdateOperatorStateParams, getOperatorByAddress *string) (*Operators, error)
	// Update operator status
	// -- invalidate: GetOperatorByAddress
	// -- timeout: 500ms
	UpdateOperatorStatus(ctx context.Context, arg UpdateOperatorStatusParams, getOperatorByAddress *string) (*Operators, error)
	// Insert or update operator record
	// -- invalidate: GetOperatorByAddress
	// -- timeout: 500ms
	UpsertOperator(ctx context.Context, arg UpsertOperatorParams, getOperatorByAddress *string) (*Operators, error)
	// Verify operator status and signing key for join request
	// -- timeout: 500ms
	VerifyOperatorStatus(ctx context.Context, address string) (*VerifyOperatorStatusRow, error)
}

var _ Querier = (*Queries)(nil)