FROM golang:1.23.3-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o operator ./cmd/operator

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/operator .
COPY start-operator.sh .
RUN chmod +x start-operator.sh
CMD ["./operator"] 