receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8889']
        
        - job_name: 'spotted-services'
          scrape_interval: 10s
          static_configs:
            - targets: 
              - 'registry:4014'  # Registry metrics
              - 'operator1:4015' # Operator1 metrics
              - 'operator2:4016' # Operator2 metrics
              - 'operator3:4017' # Operator3 metrics
          metrics_path: '/metrics'

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8888"
    namespace: "spotted"
    const_labels:
      label1: "value1"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

service:
  telemetry:
    metrics:
      level: "detailed"
      address: "0.0.0.0:8889"
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug, prometheus] 