global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'spotted-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'spotted-services'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'operator:4014'
    metrics_path: '/metrics' 