// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package consensus_responses

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConsensusResponse struct {
	ID                   int64            `json:"id"`
	TaskID               string           `json:"task_id"`
	Epoch                int32            `json:"epoch"`
	Status               string           `json:"status"`
	Value                pgtype.Numeric   `json:"value"`
	BlockNumber          pgtype.Numeric   `json:"block_number"`
	ChainID              int32            `json:"chain_id"`
	TargetAddress        string           `json:"target_address"`
	Key                  pgtype.Numeric   `json:"key"`
	AggregatedSignatures []byte           `json:"aggregated_signatures"`
	OperatorSignatures   []byte           `json:"operator_signatures"`
	TotalWeight          pgtype.Numeric   `json:"total_weight"`
	ConsensusReachedAt   pgtype.Timestamp `json:"consensus_reached_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}
