// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package consensus_responses

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConsensusResponse struct {
	ID                   int64            `json:"id"`
	TaskID               string           `json:"task_id"`
	Epoch                int32            `json:"epoch"`
	Status               string           `json:"status"`
	AggregatedSignatures []byte           `json:"aggregated_signatures"`
	OperatorSignatures   []byte           `json:"operator_signatures"`
	ConsensusReachedAt   pgtype.Timestamp `json:"consensus_reached_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}
