// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package consensus_responses

import (
	"context"
)

// TODO: change things here.
type Querier interface {
	// -- invalidate: GetConsensusResponseByTaskId
	// -- invalidate: GetConsensusResponseByRequest
	// -- timeout: 500ms
	CreateConsensusResponse(ctx context.Context, arg CreateConsensusResponseParams, getConsensusResponseByRequest *GetConsensusResponseByRequestParams) (*ConsensusResponse, error)

	// -- cache: 168h
	// -- timeout: 500ms
	GetConsensusResponseByRequest(ctx context.Context, arg GetConsensusResponseByRequestParams) (*ConsensusResponse, error)

	// -- cache: 168h
	// -- timeout: 500ms
	GetConsensusResponseByTaskId(ctx context.Context, taskID string) (*ConsensusResponse, error)
}

var _ Querier = (*Queries)(nil)
