// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package consensus_responses

import (
	"context"
)

type Querier interface {
	CreateConsensusResponse(ctx context.Context, arg CreateConsensusResponseParams) (ConsensusResponse, error)
	DeleteConsensusResponse(ctx context.Context, taskID string) error
	GetConsensusResponse(ctx context.Context, taskID string) (ConsensusResponse, error)
	ListPendingConsensus(ctx context.Context) ([]ConsensusResponse, error)
	UpdateConsensusStatus(ctx context.Context, arg UpdateConsensusStatusParams) (ConsensusResponse, error)
}

var _ Querier = (*Queries)(nil)
