// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package consensus_responses

import (
	"context"
)

type Querier interface {
	CreateConsensusResponse(ctx context.Context, arg CreateConsensusResponseParams) (ConsensusResponse, error)
	DeleteConsensusResponse(ctx context.Context, taskID string) error
	GetConsensusResponseByRequest(ctx context.Context, arg GetConsensusResponseByRequestParams) (ConsensusResponse, error)
	GetConsensusResponseByTaskId(ctx context.Context, taskID string) (ConsensusResponse, error)
	ListPendingConsensus(ctx context.Context) ([]ConsensusResponse, error)
	UpdateConsensusResponse(ctx context.Context, arg UpdateConsensusResponseParams) (ConsensusResponse, error)
}

var _ Querier = (*Queries)(nil)
