// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package epoch_states

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EpochState struct {
	EpochNumber     uint32         `json:"epoch_number"`
	BlockNumber     uint64         `json:"block_number"`
	MinimumWeight   pgtype.Numeric `json:"minimum_weight"`
	TotalWeight     pgtype.Numeric `json:"total_weight"`
	ThresholdWeight pgtype.Numeric `json:"threshold_weight"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
