// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package epoch_states

import (
	"context"
)

type Querier interface {
	GetEpochState(ctx context.Context, epochNumber uint32) (EpochState, error)
	GetLatestEpochState(ctx context.Context) (EpochState, error)
	ListEpochStates(ctx context.Context, limit int32) ([]EpochState, error)
	UpsertEpochState(ctx context.Context, arg UpsertEpochStateParams) (EpochState, error)
}

var _ Querier = (*Queries)(nil)
