// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package consensus_responses

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConsensusResponse struct {
	TaskID               string         `json:"task_id"`
	Epoch                uint32         `json:"epoch"`
	ChainID              uint32         `json:"chain_id"`
	TargetAddress        string         `json:"target_address"`
	BlockNumber          uint64         `json:"block_number"`
	Key                  pgtype.Numeric `json:"key"`
	Value                pgtype.Numeric `json:"value"`
	AggregatedSignatures [][]byte       `json:"aggregated_signatures"`
	OperatorAddresses    []string       `json:"operator_addresses"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}
