// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package blacklist

import (
	"time"
)

type Blacklist struct {
	PeerID         string     `json:"peer_id"`
	ViolationCount int32      `json:"violation_count"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	ExpiresAt      *time.Time `json:"expires_at"`
}
