// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package blacklist

import (
	"time"
)

type Blacklist struct {
	ID        int64      `json:"id"`
	PeerID    string     `json:"peer_id"`
	Ip        string     `json:"ip"`
	Reason    *string    `json:"reason"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at"`
}
