// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package task_responses

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskResponses struct {
	ID              int64          `json:"id"`
	TaskID          string         `json:"task_id"`
	OperatorAddress string         `json:"operator_address"`
	SigningKey      string         `json:"signing_key"`
	Signature       []byte         `json:"signature"`
	Epoch           uint32         `json:"epoch"`
	ChainID         uint32         `json:"chain_id"`
	TargetAddress   string         `json:"target_address"`
	Key             pgtype.Numeric `json:"key"`
	Value           pgtype.Numeric `json:"value"`
	BlockNumber     uint64         `json:"block_number"`
	Timestamp       uint64         `json:"timestamp"`
	SubmittedAt     time.Time      `json:"submitted_at"`
}
