// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package task_responses

import (
	"context"
)

type Querier interface {
	CreateTaskResponse(ctx context.Context, arg CreateTaskResponseParams) (TaskResponse, error)
	// Get specific operator's response for a task
	GetOperatorResponse(ctx context.Context, arg GetOperatorResponseParams) (TaskResponse, error)
	// Get count of responses for a task
	GetResponseCount(ctx context.Context, arg GetResponseCountParams) (int64, error)
	// Get all responses for a specific task
	GetTaskResponses(ctx context.Context, taskID string) ([]TaskResponse, error)
	// Get all responses for a task with specific status
	GetTaskResponsesByStatus(ctx context.Context, arg GetTaskResponsesByStatusParams) ([]TaskResponse, error)
	// Update response status
	UpdateResponseStatus(ctx context.Context, arg UpdateResponseStatusParams) (TaskResponse, error)
}

var _ Querier = (*Queries)(nil)
