// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package task_responses

import (
	"context"
)

// TODO: change things here.
type Querier interface {
	// -- invalidate: GetTaskResponse
	// -- timeout: 500ms
	CreateTaskResponse(ctx context.Context, arg CreateTaskResponseParams, getTaskResponse *GetTaskResponseParams) (*TaskResponses, error)
	// -- invalidate: GetTaskResponse
	// -- timeout: 500ms
	DeleteTaskResponse(ctx context.Context, arg DeleteTaskResponseParams, getTaskResponse *GetTaskResponseParams) error
	// Get single task response by task_id and operator_address
	// -- cache: 168h
	// -- timeout: 500ms
	GetTaskResponse(ctx context.Context, arg GetTaskResponseParams) (*TaskResponses, error)
	// Get recent responses for an operator, no cache for real-time data
	// -- timeout: 1s
	ListOperatorResponses(ctx context.Context, arg ListOperatorResponsesParams) ([]TaskResponses, error)
	// Get all responses for a task, no cache for real-time data
	// -- timeout: 1s
	ListTaskResponses(ctx context.Context, taskID string) ([]TaskResponses, error)
}

var _ Querier = (*Queries)(nil)
