// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.3.0-wicked-fork

package operators

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Operators struct {
	Address                 string         `json:"address"`
	SigningKey              string         `json:"signing_key"`
	P2pKey                  string         `json:"p2p_key"`
	RegisteredAtBlockNumber uint64         `json:"registered_at_block_number"`
	ActiveEpoch             uint32         `json:"active_epoch"`
	ExitEpoch               uint32         `json:"exit_epoch"`
	IsActive                bool           `json:"is_active"`
	Weight                  pgtype.Numeric `json:"weight"`
	CreatedAt               time.Time      `json:"created_at"`
	UpdatedAt               time.Time      `json:"updated_at"`
}
