// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tasks

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	TaskID        string           `json:"task_id"`
	TargetAddress string           `json:"target_address"`
	ChainID       int32            `json:"chain_id"`
	BlockNumber   pgtype.Numeric   `json:"block_number"`
	Timestamp     pgtype.Numeric   `json:"timestamp"`
	Epoch         int32            `json:"epoch"`
	Key           pgtype.Numeric   `json:"key"`
	Value         pgtype.Numeric   `json:"value"`
	ExpireTime    pgtype.Timestamp `json:"expire_time"`
	Retries       pgtype.Int4      `json:"retries"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
