// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tasks

import (
	"context"
)

type Querier interface {
	CleanupOldTasks(ctx context.Context) error
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTaskByID(ctx context.Context, taskID string) (Task, error)
	ListExpiredTasks(ctx context.Context) ([]Task, error)
	ListPendingTasks(ctx context.Context) ([]Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateTaskValue(ctx context.Context, arg UpdateTaskValueParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
